name: fastapi_test
# Triggers this workflow on pull requests to the main branch.
on:
    pull_request:
        branches:
            - main
# Uses a Windows runner, as you wanted.
jobs:
    test:
        runs-on: windows-latest
        # Here everything is in root 
        # defaults: 
        #     run:
        #         working-directory: ./main/
        
 
        strategy:
            matrix:
                python-version: [3.8]
        
        env:
            SECRET_KEY: 1234
        
        steps:
           # Clones your repo into the GitHub Actions runner.
            - uses: actions/checkout@v3

            # Install Python 3.8 as specified.
            # This action installs and configures Python on the 
            # GitHub Actions runner.
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{matrix.python-version}}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ../requirements.txt
            
            - name: Run tests
              run: python -m pytest tests